project 'test2017-10-25.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test2017-10-25' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'SDWebImage'
  # Pods for test2017-10-25

end
